//this file is used to get all the types for reducer action 
const SET_CATEGORIES = 'SET_CATEGORIES';
const GET_BANNERS = 'GET_BANNERS';
const SAVE_CATEGORY = 'SAVE_CATEGORY';
const SET_PRODUCTS= 'SET_PRODUCTS';
const SET_CART_STATUS = 'SET_CART_STATUS';
const SET_CART = 'SET_CART';
const DELETE_CART = 'DELETE_CART';
const MODIFY_CART = 'MODIFY_CART';
export {
    SET_CATEGORIES,
    GET_BANNERS,
    SAVE_CATEGORY,
    SET_PRODUCTS,
    SET_CART_STATUS,
    SET_CART,
    DELETE_CART,
    MODIFY_CART,
}